services:
  - type: web
    name: telegram-mcq-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port 10000
    envVars:
      - key: BOT_TOKEN
        value: YOUR_BOT_TOKEN
      - key: WEBHOOK_URL
        value: https://your-app-name.onrender.com
