services:
  - type: web
    name: telegram-quiz-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: BOT_TOKEN
        value: YOUR_BOT_TOKEN
        
